version: "1.0"

services:
  db:
    image: postgres:16.3
    container_name: manga
    environment:
      POSTGRES_DB: manga
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
